import functions as fun

fun.convert_xml_files_to_csv_files("fitness_stackexchange_com")
fun.convert_xml_files_to_csv_files("interpersonal_stackexchange_com")
fun.convert_xml_files_to_csv_files("worldbuilding_stackexchange_com")